"""
Pydantic schemas for the Alert & Notification Module.

AlertOut is deliberately camelCase to match Member 7's frontend Alert
interface exactly (frontend/src/types/alert.types.ts).
"""

import uuid
from datetime import datetime
from typing import Optional

from pydantic import BaseModel, EmailStr, ConfigDict, Field

from app.alerts.models import Severity, AlertStatus, AlertType


class AlertCreate(BaseModel):
    """
    Payload for raising a new alert.

    Matches the AI/Classification module's confirmed contract:
        {
          "detection_id": "...",
          "risk_score": 0-100,
          "file_id": "...",
          "malware_family": "...",
          "malware_probability": 0-1,
          "source_module": "classification"
        }
    plus a few optional extras this module adds on top (title/message are
    auto-generated by the adapter if not supplied directly).
    """

    source_reference_id: Optional[str] = None  # = detection_id
    file_id: Optional[str] = None
    file_name: Optional[str] = None
    file_hash_sha256: Optional[str] = None
    malware_family: Optional[str] = None
    risk_score: Optional[float] = Field(default=None, ge=0, le=100)
    malware_probability: Optional[float] = Field(default=None, ge=0, le=1)

    alert_type: AlertType = AlertType.MALWARE_DETECTED
    severity: Severity = Severity.MEDIUM

    title: str
    message: str
    source: str = "classification"

    recipient_user_email: Optional[EmailStr] = None


class AlertUpdateStatus(BaseModel):
    status: AlertStatus


class AlertOut(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: uuid.UUID
    title: str
    message: str
    severity: Severity
    isRead: bool
    createdAt: datetime
    source: str

    status: AlertStatus
    alertType: AlertType
    riskScore: Optional[float]
    malwareProbability: Optional[float]
    malwareFamily: Optional[str]
    fileId: Optional[str]
    fileName: Optional[str]
    fileHashSha256: Optional[str]
    sourceReferenceId: Optional[str]
    recipientUserEmail: Optional[str]
    updatedAt: Optional[datetime]
    resolvedAt: Optional[datetime]

    @classmethod
    def from_orm_alert(cls, alert) -> "AlertOut":
        return cls(
            id=alert.id,
            title=alert.title,
            message=alert.message,
            severity=alert.severity,
            isRead=alert.is_read,
            createdAt=alert.created_at,
            source=alert.source,
            status=alert.status,
            alertType=alert.alert_type,
            riskScore=alert.risk_score,
            malwareProbability=alert.malware_probability,
            malwareFamily=alert.malware_family,
            fileId=alert.file_id,
            fileName=alert.file_name,
            fileHashSha256=alert.file_hash_sha256,
            sourceReferenceId=alert.source_reference_id,
            recipientUserEmail=alert.recipient_user_email,
            updatedAt=alert.updated_at,
            resolvedAt=alert.resolved_at,
        )


class AlertStatsOut(BaseModel):
    total: int
    unread: int
    critical: int
    active: int
    resolved: int
    by_severity: dict
    by_status: dict
